import { InputMode } from "../../utility/InputUtil.js";

export const formFields = [
    { name: 'date', id: 'date-input', type: 'date', class: 'date-field' },
    { name: 'machine_number', id: 'machine-number-input', type: 'select', class: 'select-field', options: Array.from({ length: 21 }, (_, i) => (i + 1).toString()) },
    { name: 'shift', id: 'shift-input', type: 'select', class: 'select-field', options: ['A', 'B'] },
    { name: 'part_name', id: 'part-name-input', type: 'text', class: 'text-field' },
    { name: 'part_number', id: 'part-number-input', type: 'text', class: 'text-field' },
    { name: 'material', id: 'material-input', type: 'text', class: 'text-field' },
    { name: 'temperature', id: 'temperature-input', type: 'numeric', class: 'number-field' },
    { name: 'color', id: 'color-input', type: 'text', class: 'text-field' },
    { name: 'hv_limit', id: 'hv-limit-input', type: 'numeric', class: 'number-field' },
    { name: 'time_4th', id: 'time-4th-input', type: 'numeric', class: 'number-field' },
    { name: 'time_3rd', id: 'time-3rd-input', type: 'numeric', class: 'number-field' },
    { name: 'time_2nd', id: 'time-2nd-input', type: 'numeric', class: 'number-field' },
    { name: 'time_1st', id: 'time-1st-input', type: 'numeric', class: 'number-field' },
    { name: 'press_4th', id: 'press-4th-input', type: 'numeric', class: 'number-field' },
    { name: 'press_3rd', id: 'press-3rd-input', type: 'numeric', class: 'number-field' },
    { name: 'press_2nd', id: 'press-2nd-input', type: 'numeric', class: 'number-field' },
    { name: 'press_1st', id: 'press-1st-input', type: 'numeric', class: 'number-field' },
    { name: 'ret_vel', id: 'ret-vel-input', type: 'numeric', class: 'number-field' },
    { name: 'zero_set', id: 'zero-set-input', type: 'select', class: 'select-field', options: ['MODE', 'TIME', 'AUTO'] },
    { name: 'mode', id: 'mode-input', type: 'select', class: 'select-field', options: ['MODE0', 'SHARP', 'STAND.', 'SOFT', 'MODE4'] },
    { name: 'flash', id: 'flash-input', type: 'numeric', class: 'number-field' },
    { name: 'flow_check', id: 'flow-check-input', type: 'select', class: 'select-field', options: ['ON', 'OFF'] },
    { name: 'fill_t_limit', id: 'fill-t-limit-input', type: 'numeric', class: 'number-field' },
    { name: 'stage', id: 'stage-input', type: 'select', class: 'select-field', options: ['2V-2P', '5V-4P'] },
    { name: 'pos_vp', id: 'pos-vp-input', type: 'numeric', class: 'number-field' },
    { name: 'pos_4th', id: 'pos-4th-input', type: 'numeric', class: 'number-field' },
    { name: 'pos_3rd', id: 'pos-3rd-input', type: 'numeric', class: 'number-field' },
    { name: 'pos_2nd', id: 'pos-2nd-input', type: 'numeric', class: 'number-field' },
    { name: 'pos_1st', id: 'pos-1st-input', type: 'numeric', class: 'number-field' },
    { name: 'vel_vp', id: 'vel-vp-input', type: 'numeric', class: 'number-field' },
    { name: 'vel_4th', id: 'vel-4th-input', type: 'numeric', class: 'number-field' },
    { name: 'vel_3rd', id: 'vel-3rd-input', type: 'numeric', class: 'number-field' },
    { name: 'vel_2nd', id: 'vel-2nd-input', type: 'numeric', class: 'number-field' },
    { name: 'vel_1st', id: 'vel-1st-input', type: 'numeric', class: 'number-field' },
    { name: 'fill_press', id: 'fill-press-input', type: 'numeric', class: 'number-field' },
    { name: 'dose_delay', id: 'dose-delay-input', type: 'numeric', class: 'number-field' },
    { name: 'cool_time', id: 'cool-time-input', type: 'numeric', class: 'number-field' },
    { name: 'interval_time', id: 'interval-time-input', type: 'numeric', class: 'number-field' },
    { name: 'pull_back_pos', id: 'pull-back-pos-input', type: 'numeric', class: 'number-field' },
    { name: 'pull_back_vel', id: 'pull-back-vel-input', type: 'numeric', class: 'number-field' },
    { name: 'clamp_f', id: 'clamp-f-input', type: 'numeric', class: 'number-field' },
    { name: 'dose_pos_1st', id: 'dose-pos-1st-input', type: 'numeric', class: 'number-field' },
    { name: 'dose_post_2nd', id: 'dose-pos-2nd-input', type: 'numeric', class: 'number-field' },
    { name: 'dose_pos_end', id: 'dose-pos-end-input', type: 'numeric', class: 'number-field' },
    { name: 'dose_bp_1st', id: 'dose-bp-1st-input', type: 'numeric', class: 'number-field' },
    { name: 'dose_bp_2nd', id: 'dose-bp-2nd-input', type: 'numeric', class: 'number-field' },
    { name: 'dose_bp_end', id: 'dose-bp-end-input', type: 'numeric', class: 'number-field' },
    { name: 'dose_rot_1st', id: 'dose-rot-1st-input', type: 'numeric', class: 'number-field' },
    { name: 'dose_rot_2nd', id: 'dose-rot-2nd-input', type: 'numeric', class: 'number-field' },
    { name: 'dose_rot_end', id: 'dose-rot-end-input', type: 'numeric', class: 'number-field' },
    { name: 'dose_pull_back_1st', id: 'dose-pull-back-1st-input', type: 'numeric', class: 'number-field' },
    { name: 'dose_pull_back_2nd', id: 'dose-pull-back-2nd-input', type: 'numeric', class: 'number-field' },
    { name: 'dose_pull_back_delay', id: 'dose-pull-back-delay-input', type: 'select', class: 'select-field', options: ['ON', 'OFF'] },
    { name: 'open_pos_limit', id: 'open-pos-limit-input', type: 'numeric', class: 'number-field' },
    { name: 'open_pos_2nd', id: 'open-pos-2nd-input', type: 'numeric', class: 'number-field' },
    { name: 'open_pos_1st', id: 'open-pos-1st-input', type: 'numeric', class: 'number-field' },
    { name: 'open_vel_limit', id: 'open-vel-limit-input', type: 'numeric', class: 'number-field' },
    { name: 'open_vel_2nd', id: 'open-vel-2nd-input', type: 'numeric', class: 'number-field' },
    { name: 'open_vel_1st', id: 'open-vel-1st-input', type: 'numeric', class: 'number-field' },
    { name: 'close_pos_limit', id: 'close-pos-1st-input', type: 'numeric', class: 'number-field' },
    { name: 'close_pos_2nd', id: 'close-pos-2nd-input', type: 'numeric', class: 'number-field' },
    { name: 'close_pos_1st', id: 'close-pos-clamp-input', type: 'numeric', class: 'number-field' },
    { name: 'close_vel_1st', id: 'close-vel-1st-input', type: 'numeric', class: 'number-field' },
    { name: 'close_vel_2nd', id: 'close-vel-2nd-input', type: 'numeric', class: 'number-field' },
    { name: 'close_vel_clamp', id: 'close-vel-clamp-input', type: 'numeric', class: 'number-field' },
    { name: 'lw_clamp_pos', id: 'lw-clamp-pos-input', type: 'numeric', class: 'number-field' },
    { name: 'lw_clamp_press', id: 'lw-clamp-press-input', type: 'numeric', class: 'number-field' },
    { name: 'select_stage', id: 'select-stage-input', type: 'select', class: 'select-field', options: ['3', '5'] },
    { name: 'ejector_mode', id: 'ejector-mode-input', type: 'select', class: 'select-field', options: ['OFF', 'NORMAL', 'SUSP.', 'VIBRA.'] },
    { name: 'ejector_count', id: 'ejector-count-input', type: 'numeric', class: 'number-field' },
    { name: 'ejector_delay', id: 'ejector-delay-input', type: 'numeric', class: 'number-field' },
    { name: 'ejector_interval', id: 'ejector-interval-input', type: 'numeric', class: 'number-field' },
    { name: 'ejector_ret_1st', id: 'ejector-ret-1st-input', type: 'numeric', class: 'number-field' },
    { name: 'ejector_ret_2nd', id: 'ejector-ret-2nd-input', type: 'numeric', class: 'number-field' },
    { name: 'ejector_ret_3rd', id: 'ejector-ret-3rd-input', type: 'numeric', class: 'number-field' },
    { name: 'ejector_pos_1st', id: 'ejector-pos-1st-input', type: 'numeric', class: 'number-field' },
    { name: 'ejector_pos_eject', id: 'ejector-pos-eject-input', type: 'numeric', class: 'number-field' },
    { name: 'ejector_vel_1st', id: 'ejector-vel-1st-input', type: 'numeric', class: 'number-field' },
    { name: 'ejector_vel_eject', id: 'ejector-vel-eject-input', type: 'numeric', class: 'number-field' },
    { name: 'ejector_press', id: 'ejector-press-input', type: 'numeric', class: 'number-field' },
    { name: 'ejector_start', id: 'ejector-start-input', type: 'select', class: 'select-field', options: ['OPEN LIMIT', 'POS.'] },
    { name: 'ejector_start_pos', id: 'ejector-start-pos-input', type: 'numeric', class: 'number-field' },
    { name: 'ejector_hold', id: 'ejector-hold-input', type: 'select', class: 'select-field', options: ['ON', 'OFF'] },
    { name: 'eject_hold', id: 'eject-hold-input', type: 'numeric', class: 'number-field' },
    { name: 'hold_retract', id: 'hold-retract-input', type: 'numeric', class: 'number-field' },
    { name: 're_eject_hold', id: 're-eject-hold-input', type: 'numeric', class: 'number-field' },
    { name: 'molding_z5', id: 'molding-z5-input', type: 'numeric', class: 'number-field' },
    { name: 'molding_z4', id: 'molding-z4-input', type: 'numeric', class: 'number-field' },
    { name: 'molding_z3', id: 'molding-z3-input', type: 'numeric', class: 'number-field' },
    { name: 'molding_z2', id: 'molding-z2-input', type: 'numeric', class: 'number-field' },
    { name: 'molding_z1', id: 'molding-z1-input', type: 'numeric', class: 'number-field' },
    { name: 'purge_z5', id: 'purge-z5-input', type: 'numeric', class: 'number-field' },
    { name: 'purge_z4', id: 'purge-z4-input', type: 'numeric', class: 'number-field' },
    { name: 'purge_z3', id: 'purge-z3-input', type: 'numeric', class: 'number-field' },
    { name: 'purge_z2', id: 'purge-z2-input', type: 'numeric', class: 'number-field' },
    { name: 'purge_z1', id: 'purge-z1-input', type: 'numeric', class: 'number-field' },
    { name: 'lowered_z2', id: 'lowered-z2-input', type: 'numeric', class: 'number-field' },
    { name: 'lowered_z1', id: 'lowered-z1-input', type: 'numeric', class: 'number-field' },
    { name: 'range_z5', id: 'range-z5-input', type: 'numeric', class: 'number-field' },
    { name: 'range_z4', id: 'range-z4-input', type: 'numeric', class: 'number-field' },
    { name: 'range_z3', id: 'range-z3-input', type: 'numeric', class: 'number-field' },
    { name: 'range_z2', id: 'range-z2-input', type: 'numeric', class: 'number-field' },
    { name: 'range_z1', id: 'range-z1-input', type: 'numeric', class: 'number-field' },
    { name: 'on_off_z5', id: 'on-off-z5-input', type: 'select', class: 'select-field', options: ['ON', 'OFF'] },
    { name: 'on_off_z4', id: 'on-off-z4-input', type: 'select', class: 'select-field', options: ['ON', 'OFF'] },
    { name: 'on_off_z3', id: 'on-off-z3-input', type: 'select', class: 'select-field', options: ['ON', 'OFF'] },
    { name: 'on_off_z2', id: 'on-off-z2-input', type: 'select', class: 'select-field', options: ['ON', 'OFF'] },
    { name: 'on_off_z1', id: 'on-off-z1-input', type: 'select', class: 'select-field', options: ['ON', 'OFF'] },
    { name: 'water_1st', id: 'water-1st-input', type: 'numeric', class: 'number-field' },
    { name: 'water_2nd', id: 'water-2nd-input', type: 'numeric', class: 'number-field' },
    { name: 'water_3rd', id: 'water-3rd-input', type: 'numeric', class: 'number-field' },
];
